### ISSUE TITLE
Help connecting to Victron BMV-712

### ISSUE THREAD

**Issue by objectiveSee** [Olen/VictronConnect#1]
Hey @Olen! I found your project via the Victron forums! I am working on a Raspberry Pi project that connects with the BMV 712 in my van. Currently I have a Node.js process running Noble (https://github.com/abandonware/noble) however until I learn more about the Victron "API" I am only using the CLI `bluetoothctl` on the Raspberry Pi Zero W.

If you have a moment, I was hoping for some help with a few challenges that I've faced: 

1. Were you able to identify any UUIDs for a Victron BMV-712?
2. How did you determine which service has the data you need? For the BMV712 I am looking for voltage and current information. I tried looking @ the `306b0003-b081-4037-83dc-e59fcc3cdfd0` attribute, but it doesn't notify me often and I would expect it to notify me a lot, especially for changes in Current consumption. This makes me think I need to find a different UUID. I am not sure how to go about identifying the correct service. 
3. Do you have any tips for decoding the data once you found the correct service?

Thanks! :D

**Comment by objectiveSee** [comment]
A few more updates:

- Characteristic `306b0003-b081-4037-83dc-e59fcc3cdfd0` is "write without response // notify" which makes me suspect whether this is the right service. It does not send me any notifications. Perhaps I have to write a `start` command to begin receiving notifications? Any insight into this service? I don't want to write anything to my BMV until I am sure what's up.
- Characteristic ` 97580006-ddf1-48be-b73e-182664615d8e` is the only one that has a READ and NOTIFY value. It's return value is always unique, but I never get any notifications. Not sure what's up here.

**Comment by osaether** [comment]
Have you checked if the BMV-712 use LE secure connections or not? If LE secure is used you cannot get data of it without decrypting the data. Maybe you can disable the PIN-code? See "5.4 How to disable and re-enable Bluetooth" here:
https://www.victronenergy.com/live/victronconnect:start

**Comment by Olen** [comment]
Hi,
I only have one Victron device, so I only know about those UUIDs for now. 
If you look at the phoenix.py-script, you can see that I need to send some "magic" packets to a few different UUIDs before the notifications start (starting on line 200), and I also need to regularily send a special packet to keep recieving data (see line 246-255).
All of this is just a replication of what I saw that the Victron Connect app was doing, so I have not been able to actually decode exactly what each message means.

When it comes to decoding the information I received, it was mostly by "brute force".
I packet dumped the connection between the phoenix inverter and the Victron Connect App while I was connecting different loads, turning it off and on etc.
Comparing byte for byte and word for word, it was pretty easy to see what happened when I started drawing power from the inverter, and finding a number that was "close enough" to 230 (or actually 23000) to be recoginzed as what had to be output voltage * 100 (because it went to 0 when the load was disconnected), and another number that was close between 1200~1300 so I could be reasonably sure it was input voltage etc.
 
As i write in the README - the easiest is to download the VictronConnect app for Linux (or Mac, I guess) and run wireshark to catch what packes are sent over the bluetooth connection when the app monitors and manages your device.
Start by just sending the exact same packets, and see what you get back. Then you can start to "guess" what packets are really necessary, and what packets you can ignore.

**Comment by objectiveSee** [comment]
Hey! Do you mean removing the pin code, or just setting it to 00000? Also; how do you determine if the connection is secure? I've been using the LightBlue app on iOS to test the connection. Not sure what to look for in terms of it being secure or not. Appreciate the help!!

**Comment by objectiveSee** [comment]
Thanks @Olen! I'll try out WireShark (or PacketSniffer, I'm on Mac) and see what I can determine. Will post my results :)

**Comment by Olen** [comment]
Great.
My suggestion is:
- Disconnect as much load as possible from the battery (to minimize the noise in your data).
- Start the sniffer and log to a file
- Start the app
- Allow the app to settle.

Keep an eye on the BMV while you also watch the app and the packet dump.  Try to correlate what data is sent whenever the BMV and app updates with a new voltage, new current and whatever it can measure.  Take notes with timestamps and the changed values.
After a few minutes, stop the logging, and compare the lines you got whenever the voltage changed for instance.
What bytes changed, from what to what.  Do a few checks on the bytes, covert to ints - and try both big endian and little endian if more than one byte changes.  And I guess you will soon find some numbers that make sense.

**Comment by askdba** [comment]
Hi, @Olen have you resolved this?  I have a PIN number set and I can't seem to connect my devices.
```
~/solar-monitor $ ./solar-monitor.py
INFO: Adapter status - Powered: True
INFO: Starting discovery...
INFO: Found 5 BLE-devices
INFO: Trying to connect to e5:c1:6c:3f:7e:d7...
ERROR: Error importing VictronConnect
ERROR:
INFO: Trying to connect to f1:15:14:5d:57:e3...
ERROR: Error importing VictronConnect
ERROR:
INFO: Trying to connect to c8:1c:66:8e:26:ea...
ERROR: Error importing VictronConnect
ERROR:
INFO: Terminate with Ctrl+C
^CTraceback (most recent call last):
  File "./solar-monitor.py", line 108, in <module>
    device.disconnect()
NameError: name 'device' is not defined
```

I can connect these devices from `bluetoothctl` using PIN 
```
[bluetooth]# paired-devices
Device E5:C1:6C:3F:7E:D7  Inverter SVRubato
Device C8:1C:66:8E:26:EA SmartBMV SVRubato
```

Any help is appreciated.

**Comment by Olen** [comment]
This seems to be an issue with the solar-monitor which is a separate project.  Please add the issue there.
With that said, the Victron module is calle VEDirect in solar-monitor, not VictronConnect.
